(ns akarify.dict
  (:gen-class))


(def kamus ["abad"  "abadi"  "abah"  "abah-abah"  "abai"  "abang"  "abdi"  "abjad"  "abu"  "abuk"  "abung"  "acah"
                 "acapkali"  "acar"  "acara"  "aci"  "acu"  "acuh"  "acum"  "ada"  "adab"  "adang"  "adas"  "adat"  "adegan"
                 "adib"  "adik"  "adikung"  "adil"  "adinda"  "adu"  "aduh"  "aduhai"  "aduk"  "adun"  "afiat"  "afrit"
                 "agah"  "agak"  "agam"  "agama"  "agar"  "agar-agar"  "agas"  "agih"  "aguk"  "agung"  "ah"  "aha"
                 "Ahad"  "ahli"  "ahmak"  "aib"  "air"  "ais"  "ajaib"  "ajak"  "ajal"  "ajar"  "aju"  "ajuk"  "akad"
                 "akaid"  "akal"  "akan"  "akar"  "akhbar"  "akhir"  "akhirat"  "akhlak"  "akibat"  "akidah"  "akikah"
                 "akil"  "akrab"  "akta"  "aku"  "akur"  "akusaksi"  "alabangka"  "alah"  "alam"  "alamat"  "alang"
                 "alas"  "alat"  "algojo"  "alih"  "alim"  "alir"  "alis"  "aliterasi"  "alkisah"  "Allah"  "allahyarham"
                 "almarhum"  "almarhumah"  "almari"  "alpa"  "alpukat"  "alu"  "alun"  "alur"  "am"  "amah"  "amal"
                 "aman"  "amanah"  "amanat"  "amar"  "amaran"  "amat"  "ambang"  "ambil"  "amboi"  "ambul"  "ambung"
                 "amin"  "amir"  "ampai"  "ampu"  "ampun"  "amuk"  "anai"  " "  "anai-anai"  "anak"  "anasir"  "ancam"
                 "anda"  "andai"  "andam"  "andas"  "anduh"  "aneh"  "aneka"  "angan"  "angau"  "anggap"  "anggar"
                 "anggerik"  "anggota"  "angguk"  "anggur"  "angin"  "angka"  "angkara"  "angkasa"  "angkat"  "angkuh"
                 "angkup"  "angkut"  "angsa"  "aniaya"  "anjak"  "anjal"  "anjing"  "anjung"  "anjungan"  "anjur"
                 "ansur"  "antah"  "antan"  "antara"  "antarabangsa"  "antero"  "anti"  "anting"  "anu"  "anugerah"
                 "anut"  "anyam"  "apa"  "api"  "apit"  "April"  "apung"  "ara"  "arah"  "arak"  "aral"  "arang"
                 "aras"  "arca"  "ari"  "arif"  "arkib"  "arloji"  "arnab"  "arus"  "arwah"  "asa"  "asah"  "asak"
                 "asal"  "asam"  "asap"  "asar"  "asas"  "asasi"  "asin"  "asing"  "askar"  "asli"  "asmara"  "asrama"
                 "astaka"  "asuh"  "asyik"  "atap"  "atas"  "atau"  "atuk"  "atur"  "aum"  "aur"  "aurat"  "auta"  "awak"
                 "awal"  "awam"  "awan"  "awas"  "awet"  "ayah"  "ayak"  "ayak-ayak"  "ayam"  "ayan"  "ayat"
                 "ayatullah"  "ayu"  "ayun"  "azab"  "azali"  "azam"  "azan"  "azimat"  "bab"  "babad"  "babak"
                 "babas"  "babi"  "babit"  "baca"  "bacul"  "badai"  "badak"  "badam"  "badan"  "badik"
                 "badut"  "Badui"  "bagai"  "bagaimana"  "bagasi"  "baghal"  "bagi"  "baginda"  "bagur"
                 "bagus"  "bah"  "bahagi"  "bahagia"  "bahak"  "baham"  "bahan"  "bahana"  "bahang"
                 "bahantara"  "bahari"  "baharu"  "bahas"  "bahasa"  "bahawa"  "bahaya"  "bahkan"  "bahlul"
                 "bahu"  "baiduri"  "baik"  "bait"  "baitulmal"  "baja"  "bajak"  "baji"  "bajik"
                 "bajingan"  "baju"  "bak"  "baka"  "bakal"  "bakar"  "bakat"  "bakau"  "bakawali"
                 "bakhil"  "baki"  "bakti"  "baku"  "bakul"  "bakung"  "bala"  "balada"  "balah"  "balai"
                 "balak"  "balam"  "balang"  "balar"  "balas"  "baldi"  "baldu"  "baligh"  "balik"
                 "baling"  "baling-baling"  "balu"  "baluarti"  "balung"  "balut"  "banci"  "bancuh"
                 "bandar"  "bandela"  "banding"  "banduan"  "bandul"  "bangang"  "bangat"  "bangau"
                 "bangga"  "banggul"  "bangkai"  "bangkang"  "bangkit"  "bangku"  "bangsa"  "bangsal"
                 "bangsat"  "bangsawan"  "bangsi"  "bangun"  "banjar"  "banjir"  "bantah"  "bantai"
                 "bantal"  "banteras"  "banting"  "bantu"  "bantut"  "banyak"  "bapa"  "bara"
                 "barah"  "baran"  "barang"  "barangkali"  "barat"  "baring"  "baris"  "baru"
                 "barut"  "basah"  "basi"  "basmi"  "basuh"  "bata"  "batal"  "batang"  "batas"
                 "batik"  "batin"  "batu"  "batuk"  "bau"  "bauk"  "baur"  "bawa"  "bawah"  "bawal"
                 "bawang"  "baya"  "bayam"  "bayang"  "bayar"  "bayi"  "bayu"  "bazir"  "bebal"  "beban"
                 "bebas"  "bebat"  "bebawang"  "bebel"  "beberapa"  "bebibir"  "beca"  "becak"  "becok"
                 "bedah"  "bedak"  "bedal"  "bedek"  "bedil"  "beduk"  "begar"  "begini"  "begitu"
                 "beguk"  "bejana"  "bekal"  "bekam"  "bekas"  "bekat"  "beku"  "bekuan" "bela"
                 "belacan"  "belacu"  "belah"  "belai"  "belak"  "belaka"  "belakang"  "belalai"
                 "belalang"  "Belanda"  "belang"  "belanga"  "belangkas"  "belanja"  "belantan"
                 "belantara"  "belas"  "belasah"  "belat"  "belati"  "belau"  "belebas"  "belek"
                 "belengas"  "belenggu"  "belerang"  "beli"  "belia"  "beliak"  "beliau"  "belikat"
                 "belimbing"  "belit"  "beliung"  "belok"  "belot"  "belukar"  "belulang"  "belum"
                 "belut"  "bembam"  "benak"  "benam"  "benang"  "benar"  "bencana"  "benci"  "benda"
                 "bendahara"  "bendahari"  "bendalir"  "bendang"  "bendar"  "bendela"  "bendera"
                 "bendi"  "bendul"  "bendung"  "bengal"  "bengang"  "bengis"  "bengkak"  "bengkalai"
                 "bengkang"  "bengkarung"  "bengkel"  "bengkeng"  "bengkok"  "bengkung"  "benguk"
                 "benih"  "bening"  "benjol"  "bentak"  "bentan"  "bentang"  "bentar"  "bentara"
                 "benteng"  "bentuk"  "benua"  "bera"  "berahi"  "berak"  "beranda"  "berang"
                 "berangan"  "berangsang"  "berangus"  "berani"  "berapa"  "beras"  "berat"
                 "berenga"  "beres"  "Berhad"  "berhala"  "beri"  "beringin"  "berita"
                 "beritahu"  "berkas"  "berkat"  "berlian"  "bernas"  "berontak"  "beroti"  "bersih"
                 "bersin"  "bersut"  "bertih"  "beruang"  "berudu"  "beruk"  "berus"  "besan"  "besar"
                 "besi"  "besok"  "bestari"  "besut"  "beta"  "betah"  "betapa"  "betik"  "betina"
                 "beting"  "betis"  "betul"  "betung"  "beza"  "biadab"  "biak"  "biar"  "biara"
                 "bias"  "biasa"  "biasiswa"  "biawak"  "biaya"  "bibir"  "bicara"  "bicu"  "bidaah"
                 "bidadari"  "bidai"  "bidak"  "bidal"  "bidan"  "bidang"  "bidas"  "bidik"  "biduan"
                 "biduanda"  "biduanita"  "bijak"  "bijaksana"  "bijan"  "biji"  "bijih"  "bijirin"
                 "bikin"  "biku"  "bila"  "bilah"  "bilal"  "bilang"  "bilas"  "bilik"  "bilis"
                 "bimbang"  "bimbing"  "bimbit"  "bin"  "bina"  "binasa"  "binatang"  "bincang"
                 "bincut"  "bingal"  "bingit"  "bingka"  "bingkah"  "bingkai"  "bingung"
                 "bingkas"  "bingkis"  "bingung"  "bini"  "bintang"  "binti"  "bintik"
                 "bintil"  "biola"  "birai"  "biras"  "biri-biri"  "biru"  "bisa"  "bisik"  "bising"  "biskop"
                 "bistari"  "bisu"  "bisul"  "bius"  "bobok"  "bocor"  "bodoh"  "bogel"  "boh"  "bohong"  "bola"
                 "bolak-balik"  "boleh"  "bolos"  "bolot"  "bomba"  "bomoh"  "bonceng"  "bonda"  "boneka"
                 "bonggol"  "bongkah"  "bongkak"  "bongkar"  "bongkok"  "bongsu"  "bonjol"  "boo"  "bopeng"
                 "bor"  "borak"  "borang"  "borek"  "borong"  "boros"  "bosan"  "botak"  "boyak"  "boyot"
                 "buah"  "buai"  "buak"  "bual"  "buang"  "buas"  "buasir"  "buat"  "buaya"  "bubar"
                 "bubu"  "bubuh"  "bubuk"  "bubul"  "bubur"  "bucu"  "budak"  "budaya"  "budi"  "budiman"
                 "bugar"  "buih"  "bujang"  "bujuk"  "bujur"  "buka"  "bukan"  "bukit"  "bukti"  "buku"
                 "bulan"  "bulang"  "bulat"  "bulbul"  "buli-buli"  "bulu"  "buluh"  "bulur"  "bumbung"
                 "bumi"  "buncit"  "bundar"  "bunga"  "bungkal"  "bungkam"  "bungkus"  "bunian"  "buntak"
                 "buntal"  "buntang"  "buntil"  "bunting"  "buntu"  "buntut"  "bunuh"  "bunyi"  "buru"  "buruh"
                 "buruj"  "buruk"  "burung"  "burut"  "busa"  "busuk"  "busung"  "busur"  "busut"  "buta"
                 "butang"  "butir"  "buyung"  "cabai"  "cabang"  "cabar"  "cabik"  "cabul"  "cabut"
                 "cacah"  "cacak"  "cacar"  "cacat"  "caci"  "cacing"  "cadang"  "cadar"  "caduk"
                 "cagar"  "cagut"  "cahaya"  "cair"  "cakah"  "cakap"  "cakar"  "cakera"  "cekerawala"
                 "cakup"  "calar"  "calit"  "calon"  "calung"  "cam"  "camar"  "cambah"  "camca"
                 "campak"  "campur"  "canai"  "canang"  "candat"  "candu"  "cangak"  "canggah"
                 "canggih"  "canggung"  "cangkat"  "cangkir"  "cangkuk"  "cangkul"  "cangkung"
                 "cantas"  "cantik"  "cantum"  "cap"  "capai"  "capal"  "capik"  "cara"  "cari"
                 "carigali"  "carik"  "carta"  "caruk"  "carum"  "carut"  "cas"  "cat"  "catat"
                 "catu"  "catuk"  "catur"  "catut"  "cauk"  "cawak"  "cawan"  "cawangan"
                 "cawat"  "cebik"  "cebis"  "cebok"  "cebur"  "cecah"  "cecair"  "ceceh"
                 "cecekik"  "cedera"  "cedok"  "cegah"  "cegat"  "cekah"  "cekak"  "cekal"
                 "cekang"  "cekap"  "cekau"  "cekik"  "cekuh"  "cekung"  "cekup"  "cela"
                 "celaan"  "celah"  "celak"  "celaka"  "celana"  "celapak"  "celaru"  "celepa"
                 "celik"  "celopar"  "celoteh"  "celungap"  "celup"  "celur"  "celus"  "cemar"
                 "cemara"  "cemas"  "cembul"  "cembung"  "cemburu"  "cemerlang"  "cemeti"
                 "cemik"  "cempaka"  "cempedak"  "cemuh"  "cencaluk"  "cencang"  "cencorot"
                 "cendana"  "cendawan"  "cendekia"  "cendera"  "cenderamata"  "cenderawasih"
                 "cenderung"  "cendol"  "cengang"  "cengkadak"  "cengkam"  "cengkeram"
                 "cengkerama"  "cengkerik"  "cengkih"  "cengkung"  "cenuram"  "cepat"  "cepiau"
                 "cepoa"  "cepoh"  "cepu"  "cepumas"  "ceracap"  "ceracau"  "cerah"  "cerai"
                 "cerakin"  "ceramah"  "cerana"  "cerang"  "cerat"  "cerca"  "cerdas"  "cerdik"
                 "cerek"  "cereka"  "cerewet"  "cergas"  "cerita"  "cermat"  "cermin"  "cerna"
                 "ceroboh"  "cerobong"  "cerompong"  "cerpelai"  "cerpen"  "cerucuk"  "cerucup"
                 "ceruh"  "ceruk"  "cerun"  "cerut"  "cerutu"  "cetai"  "cetak"  "cetek"  "ceti"
                 "cetus"  "cicak"  "cicit"  "cicir"  "Cik"  "cikgu"  "ciku"  "Cina"  "cincin"
                 "cinta"  "cipan"  "cipta"  "ciri"  "cirit-birit"  "cita-cita"  "cium"  "cocok"
                 "cogan"  "coklat"  "cokmar"  "colek"  "coli"  "colok"  "comel"  "comot"
                 "compang-camping"  "condong"  "congak"  "congkak"  "conteng"  "contoh"
                 "copet"  "corak"  "corat-coret"  "corek"  "coreng"  "coret"  "corong"  "corot"
                 "cota"  "cuaca"  "cuai"  "cuak"  "cuba"  "cubit"  "cuci"  "cucu"  "cucuh"
                 "cucuk"  "cucunda"  "cucur"  "cuit"  "cuka"  "cukai"  "cukup"  "cukur"  "cula"
                 "culas"  "culik"  "cuma"  "cumbu"  "cungap"  "cungkil"  "cupak"  "cuping"
                 "curah"  "curam"  "curang"  "curi"  "curiga"  "curut"  "cuti"  "dabik"  "dacing"
                 "dada"  "dadah"  "dadak"  "dadih"  "dadu"  "daerah"  "daftar"  "dagang"  "daging"
                 "dagu"  "dahaga"  "daham"  "dahan"  "dahi"  "dahsyat"  "dahulu"  "daif"  "dajal"
                 "dakap"  "daki"  "dakwa"  "dakwah"  "dakwat"  "dakyah"  "dalal"  "dalam"  "dalang"
                 "dalih"  "dalil"  "dam"  "damai"  "damak"  "damar"  "dampar"  "damping"  "dan"
                 "danau"  "dandan"  "dangau"  "dangkal"  "dansa"  "dapat"  "dapur"  "dara"  "darab"
                 "darah"  "darat"  "dari"  "daripada"  "darjah"  "darjat"  "darurat"  "das"
                 "dasar"  "datang"  "datar"  "datin"  "datuk"  "daulat"  "daun"  "dawai"  "daya"
                 "dayang"  "dayu"  "dayung"  "dayus"  "debar"  "debu"  "debunga"  "debus"  "dedah"
                 "dedak"  "degil"  "dekah"  "dekan"  "dekat"  "delapan"  "delima"  "demam"  "demi"
                 "demikian"  "denai"  "denda"  "dendam"  "dendang"  "dengan"  "dengar"  "dengki"
                 "dengking"  "dengkur"  "dengung"  "dengus"  "dengut"  "denting"  "dentum"
                 "denyut"  "depa"  "depan"  "dera"  "derai"  "deram"  "derap"  "deras"  "derau"
                 "deret"  "derhaka"  "deria"  "dering"  "derita"  "derma"  "dermaga"  "deru"
                 "desa"  "desak"  "desas-desus"  "desing"  "desir"  "destar"  "desur"  "detak"
                 "detik"  "dewa"  "dewan"  "dewasa"  "dewi"  "di"  "dia"  "diam"  "dian"  "diang"
                 "didih"  "didik"  "dif"  "dikau"  "dikit"  "dinding"  "dingin"  "dinihari"  "diraja"
                 "diri"  "Disember"  "doa"  "dobi"  "dodoi"  "dodol"  "dogol"  "dompet"  "dondang"
                 "dongak"  "dongeng"  "dorong"  "dosa"  "dua"  "dubur"  "duda"  "duduk"  "duga"
                 "duit"  "duka"  "dukacita"  "dukun"  "dukung"  "dulang"  "duli"  "dungu"  "dunia"
                 "duri"  "durjana"  "dusta"  "dusun"  "duta"  "duyun"  "duyung"  "dwi"  "edar"  "eh"
                 "ehwal"  "eja"  "ejek"  "eka"  "ekanada"  "ekar"  "ekasuku"  "ekor"  "ela"  "elak"  "elok"
                 "emak"  "emas"  "embek"  "embun"  "embut"  "empang"  "empar"  "empat"  "emper"  "emping"
                 "empuk"  "empulur"  "enak"  "enam"  "enapan"  "enau"  "Encik"  "endah"  "endap"  "endul"
                 "enggan"  "enggang"  "engkau"  "engkol"  "engsel"  "engsot"  "enjal"  "entah"  "enteng"
                 "epal"  "epipusat"  "eram"  "erang"  "erat"  "Eropah"  "erti"  "esa"  "esak"  "esok"  "faedah"
                 "faham"  "faharasat"  "fajar"  "fakir"  "falak"  "falsafah"  "fana"  "faraj"  "fardu"
                 "fasal"  "fasih"  "Februari"  "fikah"  "fikir"  "Filipina"  "firasah"  "firasat"
                 "Firaun"  "firdaus"  "firman"  "fitnah"  "foya"  "furak"  "gabung"  "gabus"  "gada"
                 "gada-gada"  "gadai"  "gadang"  "gading"  "gadis"  "gado-gado"  "gaduh"  "gagah"
                 "gagak"  "gagal"  "gagang"  "gagap"  "gagas"  "gagau"  "gahara"  "gaharu"  "gait"
                 "gajah"  "gaji"  "gajus"  "gak"  "gala"  "galah"  "galak"  "galang"  "galas"  "gali"
                 "galur"  "gamak"  "gamam"  "gamang"  "gamat"  "gambang"  "gambar"  "gambus"  "gambut"
                 "gamelan"  "gamit"  "gampang"  "ganas"  "gancu"  "ganda"  "gandar"  "gandik"  "gandin"
                 "ganding"  "gandum"  "gandung"  "ganggang"  "ganggu"  "gangsa"  "ganja"  "ganjak"
                 "ganjal"  "ganjar"  "ganjil"  "gantang"  "ganti"  "gantung"  "ganyar"  "ganyang"  "gapah"
                 "gapai"  "gapura"  "garam"  "garang"  "garau"  "gari"  "garing"  "garis"  "garit"
                 "garpu"  "garu"  "garuk"  "gasak"  "gasal"  "gasang"  "gasar"  "gasing"  "gatal"  "gaul"
                 "gaung"  "gawal"  "gawang"  "gaya"  "gayat"  "gayung"  "gayut"  "gebar"  "gebu"  "gecar"
                 "gedabir"  "gedang"  "gedempol"  "gedempong"  "gedoboh"  "gedung"  "gegabah"  "gegak"
                 "gegancu"  "gegap"  "gegar"  "gegas"  "gegat"  "gegua"  "gejala"  "gejolak"  "gelabir"
                 "geladak"  "gelagat"  "gelak"  "gelambir"  "gelang"  "gelanggang"  "gelangsar"  "gelap"
                 "gelar"  "gelatuk"  "gelebar"  "gelebat"  "gelecah"  "gelecek"  "geledah"  "geledak"
                 "geledang"  "geleding"  "gelegak"  "gelegar"  "gelegata"  "gelek"  "gelekak"  "gelekek"
                 "gelema"  "geleman"  "gelembung"  "gelempang"  "gelendong"  "geleng"  "gelentang"
                 "gelepai"  "gelepar"  "gelepik"  "gelepur"  "gelesek"  "geleser"  "geletar"  "geletek"
                 "geletuk"  "geli"  "geliang-geliut"  "geliat"  "geliga"  "gelimpang"  "gelimun"  "gelincat"
                 "gelincir"  "gelincuh"  "gelinjang"  "gelintar"  "gelintir"  "gelisah"  "gelobor"
                 "gelodak"  "gelodar"  "gelojak"  "gelojoh"  "gelombang"  "gelongsor"  "gelora"
                 "gelosok"  "gelugut"  "geluh"  "gelulur"  "gelumang"  "geluncur"  "gelung"  "gelupas"
                 "gelupur"  "gelut"  "gema"  "gemal"  "gemala"  "gemalai"  "gemam"  "gemap"  "gemar"
                 "gemawan"  "gembala"  "gembereng"  "gembira"  "gembar-gembur"  "gembleng"  "gembung"
                 "gembur"  "gementar"  "gemercik"  "gemerencang"  "gemerlap"  "gemilang"  "gempa"  "gempal"
                 "gempar"  "gempita"  "gempur"  "gemuk"  "gemuruh"  "genahar"  "genang"  "genap"  "gencat"
                 "gendala"  "gendak"  "gendang"  "genderang"  "genggam"  "genggang"  "genit"  "genjang"
                 "genjot"  "genjur"  "genta"  "gentar"  "gentas"  "gentat"  "gentel"  "gentian"  "genting"
                 "genyeh"  "gepok"  "gepuh"  "gera"  "gerabak"  "geragai"  "geragas"  "geragau"  "geraham"
                 "gerai"  "gerak"  "geram"  "gerangan"  "gerantang"  "gerat"  "gerbang"  "gerecak"  "gereja"
                 "gerek"  "gerenyam"  "gergaji"  "gergasi"  "gerhana"  "geriak"  "gericau"  "geridip"
                 "gerigi"  "gerigis"  "gerimis"  "gerimit"  "gering"  "gerinjam"  "gerlap"  "gerlip"
                 "germut"  "gerenyut"  "gerobak"  "gerobok"  "gerodak"  "geromboi"  "gerombong"  "geronggang"
                 "geronyot"  "gersang"  "gertak"  "gerudi"  "gerugut"  "geruh"  "geruk"  "gerun"  "gerutu"
                 "gesa"  "gesek"  "gesel"  "geser"  "getah"  "getap"  "getar"  "getas"  "getil"  "getir"  "ghaib"
                 "ghairah"  "ghalib"  "giat"  "gigi"  "gigih"  "gigil"  "gigit"  "gila"  "gilang-gemilang"
                 "gilap"  "gilas"  "giling"  "gilir"  "gilis"  "gincu"  "ginjal"  "girang"  "giring"  "glur"
                 "gobek"  "gocoh"  "goda"  "godam"  "godok"  "gogok"  "golak"  "golek"  "golok"  "golong"
                 "gomol"  "goncang"  "gondok"  "gondol"  "gonggong"  "gonyeh"  "gonyoh"  "gopoh-gapah"
                 "goreng"  "gores"  "gosok"  "gotong-royong"  "goyah"  "goyang"  "gua"  "guam"  "guam"
                 "gubah"  "gubal"  "gubuk"  "gudang"  "gugat"  "gugup"  "gugur"  "gugus"  "gula"  "gulai"
                 "guli"  "guling"  "gulung"  "gumpal"  "guna"  "gundah"  "gundik"  "guni"  "gunting"
                 "guntur"  "gunung"  "gurau"  "gurindam"  "guru"  "guruh"  "gurun"  "gus"  "gusar"
                 "gusi"  "gusti"  "haba"  "habis"  "hablur"  "habuan"  "habuk"  "had"  "hadam"  "hadap"
                 "hadas"  "hadiah"  "hadir"  "hafaz"  "haid"  "hairan"  "haiwan"  "hajah"  "hajat"
                 "haji"  "hak"  "hakikat"  "hakiki"  "hakim"  "hakis"  "hal"  "hala"  "halaju"  "halal"
                 "halaman"  "halang"   "halau"  "halia"  "halilintar"  "halimunan"  "halkum"  "haloba"
                 "haluan"  "halus"  "halwa"  "hama"  "hamba"  "hambar"  "hambat"  "hambur"  "hambus"
                 "hamil"  "hamis"  "hampa"  "hampagas"  "hampar"  "hampas"  "hampir"  "hamput"
                 "hamun"  "hancing"  "hancur"  "handai"  "handal"  "hangat"  "hangit"  "hangus"
                 "hantam"  "hantar"  "hantu"  "hantuk"  "hanya"  "hanyir"  "hanyut"  "hanyutan"
                 "hapak"  "hapus"  "harafiah"  "haram"  "harap"  "harga"  "hari"  "harimau"  "harta"
                 "haru-biru"  "harum"  "harung"  "harus"  "hasad"  "hasil"  "hasrat"  "hasta"  "hasut"
                 "hati"  "haus"  "hawa"  "hayat"  "hebah"  "hebat"  "heboh"  "hegeh"  "hela"  "helah"
                 "helai"  "helang"  "hemah"  "hemat"  "hembus"  "hempap"  "hempas"  "hempedal"
                 "hempedu"  "hendak"  "hendap"  "hening"  "hentak"  "hentam"  "henti"  "henyak"
                 "herdik"  "heret"  "herot"  "hias"  "hiba"  "hibur"  "hidang"  "hidap"  "hidayat"
                 "hidu"  "hidung"  "hidup"  "hijau"  "hijrah"  "hikayat"  "hikmat"  "hilang"  "hilir"
                 "himpit"  "himpun"  "hina"  "hincut"  "hindar"  "hingar-bingar"  "hingus"  "hingga"
                 "hinggap"  "hinggut"  "hirau"  "hiris"  "hiruk-pikuk"  "hirup"  "hisab"  "hisap"  "hitam"
                 "hitung"  "hodoh"  "honar"  "hormat"  "hubung"  "hujah"  "hujan"  "hujung"  "hukum"
                 "hulu"  "hulubalang"  "hulur"  "huma"  "humban"  "huni"  "hunjam"  "hunus"  "hurai"
                 "huru-hara"  "huruf"  "hurung"  "hutan"  "hutang"  "huyung"  "ia"  "iaitu"  "ialah"
                 "iau"  "ibadat"  "ibarat"  "iblis"  "Ibrani"  "ibu"  "idam"  "igal"  "igau"  "ihsan"
                 "ijab"  "ijazah"  "ijtihad"  "ijuk"  "ikal"  "ikan"  "ikat"  "ikhlas"  "ikhtiar"
                 "ikhtisar"  "ikhtisas"  "ikhwan"  "iklan"  "iklim"  "ikrab"  "ikrar"  "iktibar"
                 "iktikad"  "iktiraf"  "iktisad"  "ikut"  "ilai"  "ilham"  "ilmiah"  "ilmiawan"
                 "ilmu"  "imam"  "iman"  "imbang"  "imbas"  "imbuh"  "imla"  "impi"  "imsak"  "inai"
                 "inang"  "inap"  "incar"  "inci"  "incut"  "indah"  "India"  "indik"  "inding"
                 "induk"  "inframerah"  "ingat"  "Inggeris"  "ingin"  "ingkar"  "ingus"  "ini"
                 "injak"  "Injil"  "insaf"  "insan"  "insang"  "intai"  "intan"  "intim"  "intip"
                 "intisari"  "ipar"  "irama"  "iras"  "iri"  "iring"  "iris"  "isak"  "isi"
                 "isirung"  "Islam"  "Isnin"  "istana"  "isteri"  "istiadat"  "istilah"  "istimewa"
                 "istirehat"  "isyak"  "isyarat"  "isytihar"  "itik"  "itu"  "izin"  "jaat"  "jabal"
                 "jabang"  "jabar"  "jabarut"  "jabat"  "jabel"  "jabhati"  "jabil"  "jabing"  "jabu"
                 "jabun"  "jabung"  "jabur"  "jadah"  "jadam"  "jadar"  "jadi"  "jadual"  "jae"
                 "jaga"  "jagal"  "jagang"  "jagat"  "jagoan"  "jaguh"  "jagung"  "jagur"  "jah"
                 "jahanam"  "jahang"  "jahar"  "jaharu"  "jahat"  "jahi"  "jahid"  "jahil"  "jahim"
                 "jahit"  "Jahudi"  "jail"  "jais"  "jaiz"  "jaja"  "jajah"  "jajal"  "jajan"  "jajar"
                 "jajat"  "jaksa"  "jala"  "jalad"  "jalan"  "jalar"  "jalin"  "jalur"  "jam"  "Jamadilakhir"
                 "Jamadilawal"  "jamah"  "jamak"  "jambak"  "jamban"  "jambang"  "jambat"  "jambu"
                 "jambul"  "jamin"  "jampi"  "jampuk"  "jamu"  "jana"  "janda"  "jangan"  "janggal"
                 "janggus"  "janggut"  "jangka"  "jangkau"  "jangkit"  "jangkung"  "janin"  "janji"
                 "jantan"  "jantina"  "jantung"  "jarah"  "jarak"  "jaram"  "jarang"  "jari"  "jaring"
                 "jarum"  "jasa"  "jasad"  "jasmani"  "jata"  "jati"  "jatuh"  "jauh"  "jauhari"
                 "jawa"  "jawab"  "jawat"  "Jawi"  "jaya"  "jebak"  "jeda"  "jegil"  "jejak"  "jejaka"
                 "jejambat"  "jejantas"  "jejari"  "jejas"  "jela"  "jelaga"  "jelah"  "jelajah"
                 "jelak"  "jelang"  "jelapang"  "jelas"  "jelata"  "jelatang"  "jelik"  "jeling"
                 "jelir"  "jelita"  "jelma"  "jeluas"  "jelujur"  "jemaah"  "jemala"  "jembalang"
                 "jempul"  "jemput"  "jemput-jemput"  "jemu"  "jemur"  "jenak"  "jenaka"  "jenama"
                 "jenang"  "jenayah"  "jenazah"  "jendela"  "jengah"  "jengkal"  "jengkau"  "jengkel"
                 "jengket"  "jenguk"  "jenggul"  "jenis"  "jentera"  "jentik"  "jentolak"  "jenuh"
                 "jera"  "jeram"  "jerami"  "jeran"  "jerang"  "jerangkap"  "jerangkung"  "jerat"
                 "jerawat"  "jerebu"  "jerekit"  "jerembat"  "jerempak"  "jerih"  "jeriji"  "jering"
                 "jerit"  "jerjak"  "jerkah"  "jernih"  "jeruk"  "jerumat"  "jerumus"  "jerung"  "jerut"
                 "jidal"  "jihad"  "jidar"  "jijik"  "jika"  "jikalau"  "jilat"  "jilid"  "jimak"  "jimat"
                 "jin"  "jinak"  "jingga"  "jinjang"  "jinjing"  "jintan"  "jiplak"  "jiran"  "jirat"
                 "jirus"  "jisim"  "jitu"  "jiwa"  "jodoh"  "joget"  "johan"  "jolok"  "jong"  "jongang"
                 "jongkang-jongket"  "jongkok"  "jongkong"  "joran"  "joreng"  "jorong"  "jua"  "juadah"
                 "juak"  "jual"  "juang"  "juara"  "jubah"  "jubin"  "judi"  "judul"  "juga"  "juita"
                 "jujuh"  "jujur"  "Julai"  "julang"  "julap"  "juling"  "julukan"  "julung"  "julur"
                 "Jumaat"  "jumbai"  "jumlah"  "jumpa"  "Jun"  "junam"  "junjung"  "juntai"  "jurang"
                 "juru"  "juruacara"  "juruaudit"  "juruazan"  "jurubahasa"  "jurubina"  "jurucakap"
                 "jurugambar"  "juruhebah"  "jurukamera"  "jurukira"  "jurulatih"  "jurumasak"
                 "jurumudi"  "juruoptik"  "jururawat"  "jurusawat"  "juruselam"  "jurusolek"  "jurutaip"
                 "juruteknik"  "jurutera"  "juruterbang"  "jurutrengkas"  "juruukur"  "juruulas"
                 "juruwang"  "jurus"  "justeru"  "juta"  "Kaabah"  "kabisat"  "kabu"  "kabul"  "kabung"
                 "kabur"  "kabus"  "kabut"  "kaca"  "kacak"  "kacang"  "kacau"  "kacip"  "kacuk"
                 "kacung"  "kadam"  "kadang-kadang"  "kadar"  "kadi"  "kaduk"  "kaedah"  "kafan"
                 "kafilah"  "kafir"  "kaget"  "kagum"  "kahak"  "kahwin"  "kail"  "kain"  "kais"
                 "kait"  "kajai"  "kajang"  "kaji"  "kaji"  "bintang"  "kaji"  "bumi"  "kaji"
                 "cuaca"  "kaji"  "haiwan"  "kaji"  "hayat"  "kaji"  "purba"  "kaji"  "selidik"
                 "kaji"  "tumbuhan"  "kakak"  "kakak"  "ipar"  "kakaktua"  "kakanda"  "kaki"
                 "kaki"  "ayam"  "kaki"  "bangku"  "kaki"  "bola"  "kaki"  "gaduh"  "kaki"
                 "judi"  "kaku"  "kala"  "kalah"  "kalam"  "kalang"  "kalangan"  "kalau"
                 "kalbu"  "kaldu"  "kali"  "kalimantang"  "kalimat"  "kalis"  "kalis"  "air"
                 "kalis"  "api"  "kalis"  "karat"  "kalis"  "peluru"  "kaloi"  "kalung"
                 "kalut"  "kamar"  "kambing"  "kambus"  "kami"  "kamir"  "kampit"  "kampung"
                 "kamu"  "kamus"  "kanak-kanak"  "kanan"  "kancil"  "kancing"  "kandang"
                 "kandas"  "kandung"  "kangkang"  "kanji"  "kanta"  "kantuk"  "kantung"
                 "kanun"  "kapah"  "kapai"  "kapak"  "kapal"  "kapal"  "angkasa"  "kapal"
                 "induk"  "kapal"  "korek"  "kapal"  "perang"  "kapal"  "selam"  "kapal"
                 "terbang"  "kapar"  "kapas"  "kapit"  "kapuk"  "kapung"  "kapur"  "kara"
                 "karam"  "karang"  "karat"  "karau"  "kardus"  "kari"  "karib"  "karkas"
                 "karung"  "karut"  "karya"  "kasa"  "kasap"  "kasar"  "kasi"  "kasih"
                 "kasuari"  "kasut"  "kata"  "katak"  "katik"  "katil"  "katuk"  "katung"
                 "katup"  "kau"  "kaum"  "kaus"  "kaus"  "kaki"  "kaut"  "kawah"  "kawal"
                 "kawan"  "kawasan"  "kawat"  "kawat"  "berduri"  "kaya"  "kayangan"
                 "kayap"  "kayu"  "kayuh"  "kebal"  "kebas"  "kebil"  "kebun"  "kecai"
                 "kecam"  "kecamuk"  "kecap"  "kecapi"  "kecewa"  "kecil"  "kecimpung"
                 "kecoh"  "kecuali"  "kecundang"  "kecur"  "kecut"  "kedai"  "kedal"
                 "kedang"  "kedap"  "kedek"  "kedekut"  "kedip"  "kedut"  "kehel"
                 "kejam"  "kejang"  "kejap"  "kejar"  "keji"  "Kejora"  "keju"
                 "kejur"  "kejut"  "kekal"  "kekek"  "kekang"  "kekok"  "kekuda"
                 "kelabu"  "keladak"  "keladi"  "kelah"  "kelahi"  "kelak"  "kelakar"
                 "kelalang"  "kelam"  "kelambu"  "kelamin"  "kelamun"  "kelana"  "kelangkang"
                 "kelapa"  "kelapa"  "sawit"  "kelar"  "kelasi"  "kelat"  "kelawar"
                 "keldai"  "kelecek"  "keledek"  "kelek-kelek"  "kelemayar"  "kelemayuh"
                 "kelemumur"  "kelengkeng"  "kelenjar"  "kelentang"  "kelenting"
                 "kelentong"  "kelentit"  "kelepet"  "kelepur"  "keletah"  "keli"
                 "keliar"  "kelibat"  "kelicap"  "kelikir"  "keliling"  "kelim"
                 "kelinci"  "kelip"  "kelip-kelip"  "keliru"  "kelmarin"  "kelok"
                 "kelola"  "kelompok"  "kelompong"  "kelonet"  "kelong"  "kelongsong"
                 "kelontong"  "kelopak"  "kelu"  "keluang"  "keluar"  "keluarga"  "kelubung"
                 "keluh"  "keluk"  "keluli"  "kelumit"  "kelupas"  "kemala"  "kemanakan"  "kemarau"
                 "kemaruk"  "kemas"  "kematu"  "kembali"  "kemban"  "kembang"  "kembar"
                 "kembara"  "kembiri"  "kemboja"  "kembu"  "kembung"  "kemeja"  "kemelut"
                 "kemenyan"  "kemik"  "kemis"  "kempas-kempis"  "kempis"  "kempunan"  "kemudi"
                 "kemudian"  "kemuncak"  "kemuncup"  "kena"  "kenal"  "kenan"  "kenang"
                 "kenapa"  "kencang"  "kencing"  "kencing"  "manis"  "kendali"  "kendati"
                 "kenderaan"  "kendi"  "kendong"  "kendur"  "kenduri"  "kengkang"  "kening"
                 "kenit"  "kental"  "kentang"  "kentut"  "kenyal"  "kenyang"  "kenyit"
                 "kepada"  "kepah"  "kepak"  "kepal"  "kepalan"  "kepala"  "kepalang"
                 "keparat"  "kepialu"  "kepil"  "keping"  "kepit"  "kepiting"  "kepompong"
                 "kepuk"  "kepul"  "kepung"  "kera"  "kerabat"  "kerah"  "keraian"  "kerak"
                 "kerakal"  "keramat"  "kerambit"  "keran"  "kerana"  "keranda"  "kerang"
                 "kerangka"  "kerani"  "keranjang"  "kerap"  "keras"  "kerat"  "kerawang"
                 "kerawit"  "kerbau"  "kerdil"  "kerdip"  "kerek"  "kerekot"  "kerenah"
                 "kerengga"  "kerepek"  "kereta"  "keretek"  "keria"  "kericau"  "kerikil"
                 "kering"  "keringat"  "kerinting"  "kerip"  "keris"  "kerisik"  "keriting"
                 "kerja"  "kerjaya"  "kerkah"  "kerkap"  "kerlap"  "kerling"  "kerlip"  "kernyih"
                 "keroncong"  "kerongkong"  "kerongsang"  "keropok"  "kersang"  "kersik"
                 "kertak"  "kertas"  "kertau"  "keruan"  "kerubung"  "kerudung"  "keruh"
                 "kerumun"  "keruping"  "kerusi"  "kerut"  "kerutu"  "kesah"  "kesahan"
                 "kesak"  "kesal"  "kesan"  "kesat"  "kesatria"  "kesot"  "ketak"  "ketam"
                 "ketap"  "ketar"  "ketara"  "ketat"  "ketawa"  "ketemu"  "ketiak"  "ketik"
                 "ketika"  "keting"  "ketingting"  "ketip"  "ketitir"  "ketua"  "ketuhar"
                 "ketuk"  "ketul"  "ketumbar"  "ketumbit"  "ketupat"  "khabar"  "khadam"
                 "khalayak"  "khalifah"  "khalwat"  "Khamis"  "khas"  "khasiat"  "khat"
                 "khatam"  "khatan"  "khatib"  "khatulistiwa"  "khayal"  "khazanah"
                 "khemah"  "khianat"  "khidmat"  "khilaf"  "khuatir"  "khunsa"  "khusus"
                 "khusyuk"  "khutbah"  "kial"  "kiamat"  "kiambang"  "kian"  "kias"  "kibar"
                 "kibas"  "kiblat"  "kicap"  "kicau"  "kidal"  "kijang"  "kikir"  "kikis"
                 "kilan"  "kilang"  "kilap"  "kilat"  "kilau"  "kili-kili"  "kilir"  "kimia"
                 "kimpal"  "kincir"  "kini"  "kipas"  "kira"  "kirai"  "kiri"  "kirim"
                 "kisah"  "kisar"  "kismis"  "kita"  "kitab"  "kitar"  "kitaran"  "kobar"
                 "kocak"  "kocek"  "kocok"  "kodi"  "kodok"  "kohong"  "kokok"  "kolah"
                 "kolam"  "kole"  "kolek"  "kolot"  "kompang"  "komplot"  "kongkong"
                 "kongsi"  "konon"  "kontang"  "konyong"  "kopak"  "kopek"  "kopi"  "kopiah"
                 "korban"  "korek"  "korok"  "kosong"  "kota"  "kotak"  "kotor"  "koyak"
                 "ku"  "kuaci"  "kuah"  "kuak"  "kuala"  "kuali"  "kuap"  "kuasa"  "kuat"
                 "kuatkuasa"  "kubah"  "kubang"  "kubis"  "kubu"  "kubung"  "kubur"
                 "kucai"  "kucar-kacir"  "kucing"  "kucup"  "kuda"  "kuda"  "belang"
                 "kuda-kuda"  "kudap"  "kudis"  "kudrat"  "kudung"  "kudup"  "kudus"
                 "kugiran"  "kuih"  "kuil"  "kuinin"  "kuis"  "kuit"  "kuku"  "kukuh"
                 "kukur"  "kukus"  "kulai"  "kulapuk"  "kulat"  "kuli"  "kuliah"
                 "kulit"  "kulum"  "kulup"  "kumai"  "kuman"  "kumandang"  "kumat-kamit"
                 "kumbang"  "kumis"  "kumparan"  "kumpul"  "kumuh"  "kumur"  "kunang-kunang"
                 "kunci"  "kuncup"  "kundang"  "kundur"  "kuning"  "kunjung"  "kuno"
                 "kuntum"  "kunyah"  "kunyit"  "kupang"  "kupas"  "kuping"  "kupu-kupu"
                 "kura-kura"  "kurang"  "kurap"  "kurma"  "kurnia"  "kursus"  "kurun"
                 "kurung"  "kurus"  "kusam"  "kusta"  "kusut"  "kutak"  "kutang"  "kutip"
                 "kutu"  "kutub"  "kutuk"  "kuyu"  "kuyup"  "laba"  "labah-labah"  "labang"
                 "labi-labi"  "labu"  "labuci"  "labuh"  "labur"  "laci"  "lacur"  "lada"
                 "ladam"  "ladang"  "laden"  "lading"  "lafaz"  "laga"  "lagak"  "lagang"
                 "lagi"  "lagi-lagi"  "lagipun"  "lagu"  "lahad"  "lahap"  "lahar"
                 "lahir"  "laici"  "laidaun"  "lain"  "lain-lainnya"  "lajak"  "laju"
                 "lajur"  "lakar"  "lakaran"  "laki"  "laki-laki"  "laknat"  "lakon"
                 "lakonan"  "laksa"  "laksamana"  "laksana"  "laku"  "lakur"  "lala"
                 "lalah"  "lalai"  "lalak"  "lalang"  "lalat"  "lali"  "lalu"  "lalu"
                 "lintas"  "lalu-lalang"  "laluan"  "lalut"  "lama"  "lama-lama"
                 "lama-lamaan"  "lamar"  "lamaran"  "lambai"  "lambak"  "lambang"
                 "lambat"  "lambat-laun"  "lambuk"  "lambung"  "lamin"  "lampai"
                 "lampan"  "lampau"  "lampin"  "lampir"  "lampiran"  "lampu"  "lampung"
                 "lamun"  "lamunan"  "lanar"  "lanau"  "lanca"  "lancang"  "lancar"
                 "lancip"  "lancong"  "lancung"  "lancur"  "landa"  "landai"  "landak"
                 "landas"  "landasan"  "langah"  "langak"  "langau"  "langgai"  "langgan"
                 "langganan"  "langgar"  "langit"  "langit-langit"  "langkah"  "langkan"
                 "langkas"  "langkau"  "langkup"  "langsai"  "langsing"  "langsir"
                 "langsuir"  "langsung"  "lanjur"  "lanjut"  "lanjutan"  "lantai"
                 "lantak"  "lantang"  "lantar"  "lantas"  "lantik"  "lantikan"  "lantun"
                 "lantur"  "lanun"  "lanyak"  "lap"  "lapah"  "lapan"  "lapang"
                 "lapangan"  "lapangan"  "terbang"  "lapar"  "lapik"  "lapis"  "lapisan"
                 "lapor"  "laporan"  "lapuk"  "lara"  "laram"  "larang"  "larangan"
                 "laras"  "larat"  "lari"  "larik"  "laris"  "larut"  "lasak"  "lasam"
                 "lastik"  "lata"  "latah"  "latar"  "latar"  "belakang"  "latih"
                 "latihan"  "latihan"  "asas"  "latuk"  "lau"  "burung"  "lauk"  "lauk-pauk"
                 "laung"  "laungan"  "laut"  "lautan"  "lawa"  "lawak"  "lawan"  "lawan"
                 "dalam"  "lawat"  "lawatan"  "layak"  "layan"  "layanan"  "layang-layang"
                 "layar"  "layu"  "layur"  "lazat"  "lazim"  "lebah"  "lebam"  "lebar"
                 "lebarnya"  "lebat"  "lebih"  "lebihan"  "lebih"  "kurang"  "lebih-lebih"
                 "lagi"  "lebuh"  "lebuhraya"  "lebur"  "lecah"  "leceh"  "lecek"  "lecet"
                 "lecur"  "ledak"  "ledakan"  "lega"  "legam"  "legap"  "legar"  "legeh"
                 "legup-legap"  "leher"  "leka"  "lekah"  "lekang"  "lekap"  "lekar"  "lekas"
                 "lekat"  "lekit"  "lekuk"  "lekuk-lekak"  "lekung"  "lelabah"  "lelah"
                 "lelai"  "lelaki"  "lelangit"  "lelap"  "lelas"  "lelasan"  "leleh"
                 "lelong"  "lelopak"  "leluasa"  "lelucon"  "leluhur"  "lelurah"  "lemah"
                 "lemah"  "gemalai"  "lemah"  "hati"  "lemah"  "lembut"  "lemah"  "semangat"
                 "lemak"  "lemang"  "lemas"  "lembaga"  "lembah"  "lembap"  "lembar"
                 "lembaran"  "lembik"  "lembing"  "lembu"  "lembung"  "lembur"  "lembut"
                 "lempang"  "lempar"  "lempeng"  "lempuk"  "lempung"  "lena"  "lencana"
                 "lencong"  "lencongan"  "lendap"  "lendir"  "lendung"  "lendut"  "lengah"
                 "lengan"  "lengan"  "baju"  "lengang"  "lengas"  "lenggang"  "lenggok"
                 "lengkap"  "lengkok"  "lengkuas"  "lengkung"  "lengkungan"  "lenguh"
                 "lengung"  "lentam-lentum"  "lentik"  "lenting"  "lentok"  "lentuk"
                 "lentur"  "lenyak"  "lenyap"  "lepa"  "lepak"  "lepas"  "lepasan"  "lepat"
                 "leper"  "lepuh"  "lepur"  "lerai"  "lereng"  "leret"  "lesap"  "leset"  "lesi"
                 "lesu"  "lesung"  "letak"  "leter"  "leteran"  "letih"  "letup"  "letupan"
                 "letus"  "lewat"  "liang"  "liar"  "liat"  "libat"  "libur"  "licik"  "licin"
                 "lidah"  "lidas"  "lidi"  "ligat"  "lihat"  "likat"  "liku"  "lilin"  "lilit"
                 "lilitan"  "lima"  "limau"  "limau"  "gedang"  "limau"  "nipis"  "limbang"
                 "limbungan"  "limpa"  "limpah"  "limpap"  "linang"  "lincah"  "lincir"
                 "lindung"  "lindungan"  "lingga"  "lingkar"  "lingkaran"  "lingkung"
                 "lingkungan"  "lingkup"  "lintah"  "lintang"  "lintang-pukang"  "lintas"
                 "lipan"  "lipas"  "lipat"  "lipatan"  "lipit"  "lipur"  "liput"  "liputan"
                 "lisan"  "lisut"  "litar"  "litup"  "liuk"  "liwat"  "loba"  "lobak"  "lobak"
                 "merah"  "loceng"  "lodak"  "lodeh"  "logam"  "logamaya"  "loghat"  "lohong"
                 "loji"  "lok"  "lokek"  "lolong"  "lombong"  "lombong"  "bijih"  "lompang"
                 "lompat"  "lompatan"  "lompat"  "bergalah"  "lompat"  "jauh"  "lompat"  "kijang"
                 "lompat"  "tinggi"  "loncat"  "loncatan"  "londeh"  "long"  "longgar"
                 "longgok"  "longgokan"  "longkah"  "longkang"  "longlai"  "lonjak"
                 "lonjakan"  "lonjong"  "lontar"  "lontong"  "lopak"  "lopong"  "lorek"
                 "lori"  "lorong"  "loteng"  "lotong"  "loya"  "loyang"  "luah"  "luak"  "luang"
                 "luap"  "luar"  "luaran"  "luar"  "bandar"  "luar"  "batas"  "luar"  "biasa"  "luar"
                 "dalam"  "luar"  "negara"  "luar"  "nikah"  "luas"  "luat"  "lubang"  "lubuk"
                 "lucah"  "lucu"  "lucut"  "ludah"  "luhur"  "luka"  "lukah"  "lukis"  "lukisan"
                 "luluh"  "lulur"  "lulus"  "lumang"  "lumas"  "lumat"  "lumayan"  "lumba"
                 "lumba-lumba"  "lumpuh"  "lumpur"  "lumrah"  "lumur"  "lumuran"  "lumut"
                 "lunak"  "lunas"  "luncur"  "lundi"  "lungkup"  "lungsur"  "lunjur"  "luntur"
                 "lupa"  "luput"  "lurah"  "luru"  "luruh"  "lurus"  "lurut"  "lusa"  "lusuh"
                 "lut"  "lutcahaya"  "lutsinar"  "lutut"  "luyu"  "maaf"  "maafkan"  "saya"  "mabuk"
                 "mabuk"  "asmara"  "mabuk"  "laut"  "Mac"  "macam"  "macang"  "madah"  "madat"
                 "madrasah"  "madu"  "maghrib"  "maging"  "maha"  "mahaguru"  "maha"  "kuasa"  "mahal"
                 "mahar"  "maharaja"  "maharani"  "mahasiswa"  "maharajalela"  "mahir"  "mahkamah"
                 "mahkota"  "mahligai"  "mahsul"  "mahu"  "mahupun"  "main"  "mainan"  "majal"  "majalah"
                 "majikan"  "majlis"  "majmuk"  "maju"  "mak"  "mak"  "angkat"  "makcik"  "mak"  "tiri"
                 "maka"  "makam"  "makan"  "makanan"  "makbul"  "makhluk"  "maki"  "makian"  "makin"
                 "maklum"  "maklumat"  "makmal"  "makmur"  "makna"  "makruf"  "maksiat"  "maksud"
                 "maktab"  "maktub"  "malah"  "malahan"  "malaikat"  "malam"  "malam"  "minggu"
                 "malang"  "malangnya"  "malap"  "malapetaka"  "malar"  "malas"  "malik"  "malim"
                 "malu"  "malung"  "mamah"  "mamak"  "mambang"  "mampat"  "mampu"  "mampus"  "mana"
                 "mana"  "satu"  "mana-mana"  "mancis"  "mancung"  "mancur"  "mandi"  "mandul"
                 "mandur"  "manfaat"  "mangga"  "manggar"  "manggis"  "mangkat"  "mangkin"  "mangku"
                 "mangkuk"  "mangsa"  "mangu"  "mani"  "manik"  "manikam"  "manis"  "manisan"
                 "manja"  "manjur"  "mansit"  "mansuh"  "mantap"  "mantera"  "manusia"  "mara"
                 "marah"  "marak"  "mari"  "Marikh"  "markah"  "markas"  "marmar"  "marmut"
                 "martabak"  "martabat"  "maruah"  "masa"  "masa"  "depan"  "masa"  "lalu"
                 "masa"  "silam"  "masak"  "masakan"  "masalah"  "masam"  "maserba"  "masih"
                 "masin"  "masing-masing"  "masjid"  "mastautin"  "masuk"  "masuk"  "campur"
                 "masyarakat"  "masyghul"  "masyhur"  "mata"  "mata"  "air"  "mata"  "hitam"
                 "mata"  "wang"  "matahari"  "mata-mata"  "matang"  "matarah"  "mati"  "mati-matian"
                 "matlamat"  "maujud"  "maun"  "maung"  "maut"  "mawar"  "maya"  "mayam"  "mayang"
                 "mayat"  "mazhab"  "mazmur"  "medan"  "medan"  "perang"  "megah"  "Mei"  "meja"
                 "mekar"  "melaka"  "melarat"  "melati"  "Melayu"  "meleset"  "melukut"  "melulu"
                 "melur"  "memang"  "memar"  "memerang"  "mempelai"  "mempelam"  "menang"  "menantu"
                 "menara"  "mendak"  "mendap"  "mendapan"  "mendiang"  "mendung"  "mengah"  "mengkal"
                 "mentadak"  "mentah"  "mentang-mentang"  "mentega"  "menteri"  "mentimun"  "mentua"
                 "mentul"  "menung"  "merah"  "merah"  "jambu"  "merah"  "lembayung"  "merah"  "manggis"
                 "merak"  "merana"  "merbah"  "merbuk"  "mercu"  "mercun"  "merdeka"  "merdu"  "mereka"
                 "mergastua"  "meriah"  "meriam"  "merinyu"  "merosot"  "merpati"  "mersik"  "Mesir"
                 "meskipun"  "mesra"  "mesti"  "mestika"  "mesyuarat"  "meterai"  "mewah"  "mi"  "miang"
                 "milik"  "mimbar"  "mimpi"  "minat"  "minggu"  "mingguan"  "minta"  "minum"  "minuman"
                 "minuman"  "keras"  "minuman"  "ringan"  "minyak"  "minyak"  "sapi"  "minyak"  "tanah"
                 "miring"  "mirip"  "misai"  "misal"  "miskin"  "modal"  "moga-moga"  "mogok"  "mogok"
                 "lapar"  "mohon"  "mohor"  "molek"  "momok"  "mongel"  "montel"  "montok"  "monyet"
                 "moyang"  "mu"  "muafakat"  "muak"  "mual"  "mualim"  "muara"  "muat"  "muatan"
                 "muazam"  "muazin"  "mubaligh"  "muda"  "mudah"  "mudah-mudahan"  "mudarat"
                 "mudik"  "muflis"  "mufti"  "Muharam"  "muhibah"  "mujarab"  "mujur"  "muka"
                 "muka"  "depan"  "muka-muka"  "muka"  "pintu"  "muka"  "selamba"  "muka"  "surat"
                 "muka"  "tebal"  "mukah"  "mukim"  "mukjizat"  "muktamad"  "muktamar"  "mula"  "mulai"
                 "mula-mula"  "mulas"  "mulia"  "mulur"  "mulut"  "mulut"  "manis"  "mulut"  "murai"
                 "mumbang"  "munafik"  "munasabah"  "muncul"  "muncung"  "mundar-mandir"  "mundur"
                 "mungil"  "mungkar"  "mungkin"  "mungkir"  "munsyi"  "muntah"  "murah"  "murah"
                 "hati"  "murai"  "muram"  "murid"  "murka"  "murni"  "murtad"  "murung"  "musafir"
                 "musang"  "musim"  "muslihat"  "Muslim"  "Muslimat"  "musnah"  "mustahak"  "mustahil"
                 "mustajab"  "musuh"  "Musytari"  "mutakhir"  "mutiara"  "mutlak"  "mutu"  "muzakarah"
                 "nabi"  "nada"  "nadi"  "nafas"  "nafi"  "nafkah"  "nafsu"  "naga"  "nahas"  "nahu"
                 "naib"  "naik"  "najis"  "nak"  "nakal"  "nakhoda"  "naluri"  "nama"  "nampak"  "namun"
                 "nanah"  "nanas"  "nangka"  "nanti"  "nasab"  "nasi"  "nasib"  "nasihat"  "naskhah"
                 "Nasrani"  "natijah"  "naung"  "nazak"  "nazar"  "nazir"  "negara"  "negeri"  "nekad"
                 "nelayan"  "nenek"  "neraca"  "neraka"  "nescaya"  "nganga"  "ngeri"  "ngiang"  "ngiau"
                 "ngilu"  "nguak"  "niaga"  "niat"  "nikah"  "nikmat"  "nila"  "nilai"  "nilam"  "nipah"
                 "nipis"  "nirinsani"  "nirwana"  "nisan"  "nisbah"  "niskala"  "nista"  "nobat"  "noda"
                 "noktah"  "nombor"  "nona"  "nota"  "November"  "nujum"  "nusa"  "Nusantara"  "nya"
                 "nyah"  "nyahcas"  "nyahjangkit"  "nyahpecutan"  "nyala"  "nyaman"  "nyamuk"  "nyanyi"
                 "nyanyuk"  "nyaring"  "nyaris"  "nyata"  "nyawa"  "nyenyak"  "nyiru"  "nyiur"  "nyonya"
                 "nyunyut"  "obor"  "oceh"  "ogah"  "Ogos"  "oh"  "oi"  "Oktober"  "olah"  "olahraga"
                 "olakan"  "oleh"  "oleng"  "olok-olok"  "ombak"  "omel"  "omong"  "onar"  "onde-onde"
                 "ongkos"  "ooh"  "opah"  "orang"  "oren"  "otak"  "otot"  "pacak"  "pacal"  "pacat"
                 "pacul"  "pada"  "padah"  "padam"  "padan"  "padanan"  "padang"  "padang"  "pasir"
                 "padat"  "paderi"  "padi"  "padu"  "paduka"  "pagar"  "pagi"  "pagi-pagi"  "pagut"
                 "paha"  "pahala"  "pahat"  "pahit"  "pahlawan"  "pajak"  "pajak"  "gadai"  "pak"
                 "pakcik"  "pakai"  "pakaian"  "pakaian"  "seragam"  "pakal"  "pakar"  "pakar"
                 "runding"  "pakat"  "pakatan"  "pakis"  "paksa"  "paksaan"  "paksi"  "paku"
                 "pala"  "palam"  "palang"  "paling"  "palit"  "palsu"  "palu"  "paluan"  "palung"
                 "palut"  "pamah"  "paman"  "pamer"  "pameran"  "pampang"  "pampas"  "pampasan"
                 "panah"  "panahan"  "panas"  "panas"  "terik"  "panas-panas"  "panau"  "panca"
                 "pancalogam"  "pancaindera"  "pancang"  "pancar"  "pancaran"  "pancaragam"  "pancing"
                 "pancit"  "pancung"  "pancungan"  "pancur"  "pancut"  "pancutan"  "pandai"  "pandan"
                 "pandang"  "pandangan"  "pandang-memandang"  "pandir"  "pandu"  "panduan"  "pandu"
                 "puteri"  "panggang"  "panggil"  "panggilan"  "panggung"  "panggung"  "wayang"
                 "pangkah"  "pangkal"  "pangkalan"  "pangkas"  "pangkat"  "pangkin"  "pangku"
                 "pangkuan"  "panglima"  "pangsa"  "pangsapuri"  "panitia"  "panjang"  "panjang"
                 "akal"  "panjangnya"  "panjat"  "panji-panji"  "pantai"  "pantang"  "pantang"
                 "larang"  "pantas"  "pantat"  "pantul"  "pantulan"  "pantun"  "papa"  "papa"
                 "kedana"  "papah"  "papan"  "papan"  "catur"  "papan"  "hitam"  "papan"  "iklan"
                 "papan"  "kenyataan"  "papar"  "papas"  "para"  "para-para"  "parah"  "parang"
                 "paras"  "parau"  "pari"  "pari-pari"  "parit"  "paru-paru"  "paruh"  "parut"
                 "pasak"  "pasang"  "pasangan"  "pasang"  "badan"  "pasang"  "telinga"  "pasar"
                 "pasar"  "borong"  "pasar"  "gelap"  "pasar"  "malam"  "pasaraya"  "pasir"  "pasti"
                 "pasu"  "pasu-pasu"  "pasukan"  "pasung"  "patah"  "patah"  "hati"  "pateri"  "pati"  "patik"
                 "patuh"  "patuk"  "patung"  "patung-patung"  "patut"  "paus"  "paut"  "pawagam"  "pawah"
                 "pawang"  "paya"  "paya"  "bakau"  "payah"  "payau"  "payung"  "pecah"  "pecahan"
                 "pecat"  "pecut"  "pedang"  "pedap"  "pedas"  "pedati"  "pedih"  "pedoman"  "peduli"
                 "pegaga"  "pegang"  "pegangan"  "pegawai"  "peguam"  "peguambela"  "peguamcara"
                 "pegun"  "pejal"  "pejalwapan"  "pejam"  "peka"  "pekak"  "pekan"  "pekap"  "pekasam"
                 "pekat"  "pekerti"  "pekik"  "pelamin"  "pelampung"  "pelana"  "pelanduk"  "pelangi"
                 "pelantar"  "pelanting"  "pelat"  "pelawa"  "pelawaan"  "pelbagai"  "pelecok"
                 "pelekat"  "pelepah"  "pelesir"  "pelihara"  "peliharaan"  "pelik"  "pelita"
                 "pelopor"  "pelosok"  "peluang"  "peluh"  "peluk"  "pelukan"  "peluru"  "pena"
                 "penat"  "penawar"  "pencak"  "pencil"  "pendam"  "pendaman"  "pendek"  "pendekar"
                 "pendita"  "pengantin"  "pengaruh"  "penggal"  "penggawa"  "penghulu"  "pengsan"
                 "pening"  "pening-pening"  "lalat"  "peniti"  "penjara"  "penjuru"  "pentas"
                 "penting"  "penuh"  "penyek"  "penyu"  "pepatah"  "perabot"  "perah"  "perahan"
                 "perahu"  "perajurit"  "perak"  "peraka"  "peram"  "peran"  "peranan"  "Perancis"
                 "perang"  "peperangan"  "perangai"  "perangkap"  "peranjat"  "perap"  "peras"
                 "perasan"  "perawan"  "perca"  "percaya"  "percik"  "percuma"  "perdana"  "perdu"
                 "perempuan"  "perencah"  "perenggan"  "pergi"  "peri"  "peri-peri"  "peria"
                 "peribadi"  "peribahasa"  "peribumi"  "perigi"  "perigi"  "buta"  "perihal"
                 "perikemanusiaan"  "periksa"  "perinci"  "peringkat"  "perintah"  "perisai"
                 "peristiwa"  "perit"  "periuk"  "perkakas"  "perkara"  "perkasa"  "perkosa"
                 "perkosaan"  "perlahan"  "perli"  "perlu"  "permai"  "permaidani"  "permaisuri"
                 "permata"  "pernah"  "peroi"  "peronyok"  "perosok"  "persegi"  "pertama"
                 "perut"  "perwira"  "pesan"  "pesanan"  "pesat"  "pesawat"  "pesisir"
                 "pesona"  "pesong"  "pesta"  "pesuruhjaya"  "peta"  "petah"  "petai"
                 "petak"  "petala"  "petaling"  "petang"  "peti"  "peti"  "sejuk"  "peti"
                 "surat"  "petik"  "petikan"  "petola"  "petir"  "petua"  "piagam"  "piala"
                 "piat"  "piatu"  "piawai"  "picagari"  "picing"  "picit"  "pidato"  "pihak"
                 "pijak"  "pijat"  "pikat"  "pikul"  "pilin"  "pilih"  "pilihan"  "pilihanraya"
                 "pilu"  "pimpin"  "pimpinan"  "pinang"  "pinar"  "pincang"  "pinda"  "pindaan"
                 "pindah"  "pindah"  "milik"  "pindah"  "tangan"  "pindahan"  "pinga"  "pingat"
                 "pinggan"  "pinggan"  "mangkuk"  "pinggang"  "pinggir"  "pinggir"  "jalan"
                 "pinggir"  "kota"  "pinggir"  "laut"  "pinggul"  "pinjam"  "pinjaman"  "pinta"
                 "pintal"  "pintar"  "pintas"  "pintasan"  "pintu"  "pipi"  "pipih"  "pipis"  "pipit"
                 "piring"  "piring"  "hitam"  "pisah"  "pisang"  "pisau"  "pita"  "pitam"  "piutang"
                 "plumbum"  "pohon"  "pokok"  "pondan"  "pondok"  "ponteng"  "pontianak"
                 "porak-peranda"  "potong"  "potongan"  "prakata"  "pramugara"  "pramugari"
                 "prasangka"  "prasejarah"  "prestasi"  "puak"  "puaka"  "puan"  "puas"
                 "puasa"  "pucat"  "pucuk"  "pudar"  "puding"  "puisi"  "puja"  "pujangga"
                 "puji"  "pujian"  "pujuk"  "pujukan"  "pukal"  "pukang"  "pukat"  "pukau"
                 "pukul"  "pula"  "pulang"  "pulangan"  "pulang"  "kerahmatullah"  "pulas"
                 "pulau"  "pulih"  "puluh"  "pulut"  "pun"  "punah"  "punai"  "punat"  "punca"
                 "puncak"  "pundi-pundi"  "pundi-pundi"  "kencing"  "punggah"  "pungguk"
                 "punggung"  "pungut"  "pungutan"  "puntal"  "puntung"  "punya"  "pupu"
                 "pupuk"  "pupus"  "pura-pura"  "purata"  "purba"  "purbakala"  "purdah"
                 "puri"  "purnama"  "pusaka"  "pusar"  "pusaran"  "pusara"  "pusat"
                 "pusing"  "pusingan"  "puspa"  "pustaka"  "pustakawan"  "putar"
                 "putaran"  "putera"  "puteri"  "putih"  "putih"  "kuning"  "putik"
                 "puting"  "puting"  "beliung"  "putus"  "puyu"  "puyuh"  "qada"  "qari"
                 "qariah"  "Quran"  "raba"  "rabak"  "Rabiulakhir"  "Rabiulawal"  "rabik"
                 "rabit"  "Rabu"  "rabuk"  "rabun"  "rabun"  "dekat"  "rabun"  "jauh"
                 "rabung"  "racik"  "racikan"  "racun"  "radak"  "radang"  "radas"  "raden"
                 "raga"  "ragam"  "ragi"  "ragu-ragu"  "ragum"  "ragut"  "rahang"  "rahim"
                 "rahmat"  "rahmati"  "rahsia"  "rai"  "raih"  "raja"  "Raja"  "Muda"
                 "raja"  "sehari"  "rajah"  "rajau"  "rajawali"  "rajin"  "rajuk"  "rakam"
                 "rakaman"  "rakan"  "rakit"  "raksa"  "raksasa"  "rakus"  "rakyat"  "ralat"
                 "rama-rama"  "Ramadan"  "ramah"  "ramai"  "ramal"  "ramalan"  "ramas"
                 "rambang"  "rambang"  "mata"  "rambu-rambu"  "rambut"  "rami"  "rampai"
                 "rampas"  "ramping"  "rampok"  "ramu"  "ramuan"  "ranap"  "rancak"  "rancang"
                 "rancangan"  "randuk"  "rang"  "rang"  "undang-undang"  "rangka"
                 "rangkai"  "rangkak"  "rangkap"  "rangking"  "rangkul"  "rangkum"
                 "rangsang"  "rangup"  "ranjang"  "ranjau"  "rantai"  "rantai"  "leher"
                 "rantai"  "tangan"  "rantaian"  "rantau"  "ranting"  "ranum"  "rapat"
                 "rapi"  "rapuh"  "rasa"  "rasi"  "rasmi"  "rasuah"  "rasuk"  "rasul"
                 "rata"  "ratap"  "ratapan"  "ratna"  "ratu"  "ratus"  "raung"  "raungan"
                 "raup"  "raut"  "rawak"  "rawan"  "rawat"  "rawatan"  "raya"  "rayap"
                 "rayau"  "rayu"  "rayuan"  "rebah"  "rebak"  "reban"  "rebas"  "rebung"
                 "rebus"  "rebut"  "recih"  "recik"  "reda"  "redah"  "redaksi"  "redup"
                 "regang"  "regu"  "rehat"  "reja"  "Rejab"  "rejam"  "reka"  "reka"  "bentuk"
                 "rekaan"  "rekah"  "rekahan"  "rekat"  "rela"  "relau"  "remah"  "remaja"
                 "remang"  "rembat"  "rembes"  "rembesan"  "remeh-temeh"  "rempah"  "rempak"
                 "rempang-lempung"  "rempuh"  "rempuhan"  "remuk"  "remuk"  "hati"  "remuk-redam"
                 "renang"  "rencah"  "rencana"  "rencat"  "renda"  "rendah"  "rendam"  "rendang"
                 "renek"  "renggang"  "rengus"  "renjis"  "rentak"  "rentang"  "rentap"  "rentas"
                 "rentetan"  "renung"  "renungan"  "renyai"  "renyuk"  "renyuk-renyik"  "repek"
                 "reput"  "resah"  "resam"  "resap"  "restu"  "retak"  "retakan"  "retas"  "rezeki"
                 "ria"  "riadah"  "riak"  "riang"  "riba"  "ribu"  "ribut"  "ridip"  "rimas"  "rimba"
                 "rimbun"  "rinci"  "rindu"  "rindu"  "dendam"  "ringan"  "ringan"  "mulut"  "ringan"
                 "tangan"  "ringan"  "tulang"  "Ringgit"  "Malaysia"  "ringkas"  "ringkasan"  "ringkasnya"
                 "ringkuk"  "rintang"  "rintangan"  "rintih"  "rintihan"  "rintik"  "rintik-rintik"
                 "rintis"  "risalah"  "risau"  "risik"  "riuh"  "riwayat"  "riwayat"  "hidup"
                 "robek"  "roboh"  "roda"  "rodok"  "rogol"  "roh"  "rohani"  "rohaniah"
                 "rojak"  "rokok"  "roma"  "roman"  "rombak"  "rombakan"  "rombong"
                 "rombongan"  "rompak"  "rompakan"  "rompong"  "ronda"  "rongak"  "rongga"
                 "ronggeng"  "rongkong"  "ronta"  "rosak"  "rosot"  "rotan"  "roti"  "ruam"
                 "ruam"  "panas"  "ruam"  "saraf"  "ruang"  "ruangan"  "ruang"  "makan"
                 "ruang"  "waktu"  "ruap"  "ruas"  "rugi"  "ruji"  "rujuk"  "rujukan"  "rukun"
                 "rumah"  "rumah"  "tangga"  "rumbia"  "Rumi"  "rumit"  "rumpai"  "rumpair"  "rumpun"
                 "rumput"  "rumus"  "runcing"  "runcit"  "runding"  "rundingan"  "rungut"  "rungutan"
                 "runsing"  "runtuh"  "runtun"  "runtunan"  "rupa"  "rupa"  "kata"  "rupa"  "nama"
                 "rupanya"  "rupawan"  "rusa"  "rusa"  "senggerik"  "rusuh"  "rusuhan"  "rusuk"  "saat"
                 "saban"  "sabar"  "sabda"  "sabit"  "Sabtu"  "sabun"  "sabung"  "sabungan"
                 "sabung-menyabung"  "sabut"  "sadai"  "sadap"  "saderi"  "sadur"  "saga"  "sagat"
                 "sagu"  "sah"  "sahabat"  "sahaja"  "saham"  "sahih"  "sahsiah"  "sahur"  "sahut"
                 "sahutan"  "saing"  "sajak"  "saji"  "sajian"  "sakat"  "saki-baki"  "sakit"  "sakit"
                 "hati"  "saksama"  "saksi"  "sakti"  "saku"  "salah"  "salai"  "salak"  "salam"
                 "salang"  "salangkan"  "salasilah"  "salib"  "salih"  "salin"  "salinan"  "saling"
                 "salir"  "saliran"  "salji"  "salur"  "saluran"  "salur"  "darah"  "salur"  "kencing"
                 "salur"  "mani"  "salur"  "nadi"  "salut"  "salut"  "bunga"  "sama"  "samak"  "samar"
                 "sambal"  "sambar"  "sambil"  "sambilan"  "sambil"  "lalu"  "sambung"  "sambungan"
                 "sambut"  "sambutan"  "sami"  "sampah"  "sampah"  "sarap"  "sampai"  "sampai"  "hati"
                 "sampan"  "samping"  "sampingan"  "sampuk"  "sampul"  "samseng"  "samudera"  "samun"
                 "sana"  "sanak"  "saudara"  "sandang"  "sandar"  "sandar-menyandar"  "sandaran"
                 "sanding"  "sandiwara"  "sang"  "sangat"  "sangga"  "sanggah-menyanggah"  "sanggama"
                 "sanggul"  "sanggup"  "sangka"  "sangkaan"  "sangkak"  "sangkal"  "sangkalan"  "sangkar"
                 "sangkut"  "sangkut-paut"  "sangsi"  "sanjung"  "sanjungan"  "santai"  "santan"  "santap"
                 "santapan"  "santun"  "sanubari"  "sapa"  "sapaan"  "sapi"  "sapu"  "sapu"  "tangan"  "sara"
                 "sara"  "hidup"  "saraf"  "saran"  "saranan"  "sarang"  "sarap"  "sarapan"  "sarat"  "saribunga"
                 "saring"  "saringan"  "sarjana"  "sarjana"  "muda"  "sarung"  "sasa"  "sasar"  "sasaran"
                 "sastera"  "sasterawan"  "sasterawati"  "sasul"  "satah"  "satu"  "satu-satu"  "satu-satunya"
                 "saudagar"  "saudara"  "saudara-mara"  "saudari"  "sauh"  "saujana"  "sauk"  "sawah"
                 "sawan"  "sawang"  "sawat"  "saya"  "sayang"  "sayap"  "sayat"  "sayu"  "sayup"  "sayup-sayup"
                 "sayur"  "sayur-sayuran"  "sayur-mayur"  "se"  "sebab"  "sebab-musabab"  "sebak"  "sebal"
                 "sebar"  "sebaran"  "sebat"  "sebatan"  "sebaya"  "seberang"  "sebu"  "sebut"  "sebutan"
                 "sedak"  "sedang"  "sedap"  "sedar"  "sedekah"  "sederhana"  "sedia"  "sediakala"  "sedih"
                 "sedu"  "sedu-sedan"  "sedut"  "sedutan"  "segak"  "segala"  "segala-galanya"  "segan"
                 "segan-silu"  "segar"  "segar-bugar"  "segera"  "segi"  "segi"  "empat"  "segi"  "tiga"
                 "segi"  "tiga"  "sama"  "kaki"  "segi"  "tiga"  "sama"  "sisi"  "sejahtera"  "sejak"
                 "sejarah"  "sejat"  "sejuk"  "sekaligus"  "sekalipun"  "sekam"  "sekarang"  "sekat"
                 "sekatan"  "sekerap"  "sekoi"  "sekolah"  "sekongkol"  "seksa"  "seksaan"  "sekutu"
                 "sela"  "seladang"  "selak"  "selalu"  "selam"  "selamat"  "selamat"  "datang"
                 "selamat"  "jalan"  "selamat"  "malam"  "selamat"  "pagi"  "selamba"  "selang"
                 "selaput"  "selaput"  "mata"  "selar"  "Selasa"  "selasih"  "selat"  "selatan"
                 "selawat"  "selekeh"  "selekoh"  "selempang"  "selendang"  "selenggara"  "selera"
                 "selerak"  "selesa"  "selesai"  "seleweng"  "selia"  "selidik"  "selimut"  "selinap"
                 "selindung"  "seling"  "selingan"  "selirat"  "selisih"  "selit"  "seliuh"
                 "selok"  "selok-belok"  "selongkar"  "seloroh"  "selsema"  "seluar"  "seluar"
                 "dalam"  "selubung"  "seludup"  "seluk"  "selumbar"  "seluruh"  "selusup"
                 "selut"  "semadi"  "semai"  "semaian"  "semak"  "semak-samun"  "semangat"
                 "semangka"  "semarak"  "semat"  "semayam"  "sembah"  "sembah"  "salam"
                 "sembahyang"  "sembam"  "sembang"  "sembap"  "sembarang"  "sembarangan"
                 "sembelih"  "sembelihan"  "sembelit"  "sembilan"  "semboyan"  "sembuh"
                 "sembul"  "sembunyi"  "sembur"  "semenanjung"  "semenjak"  "semenjak"
                 "itu"  "sementara"  "sementara"  "itu"  "semerbak"  "semesta"  "semesta"
                 "alam"  "sempadan"  "sempang"  "sempat"  "sempena"  "sempit"  "sempurna"
                 "semua"  "semuanya"  "semut"  "sen"  "senak"  "senak"  "perut"  "senam"
                 "senaman"  "senang"  "senapang"  "senarai"  "senda"  "sendat"  "sendawa"
                 "sendeng"  "sendi"  "sendiri"  "sendiri-sendiri"  "senduk"  "sengaja"
                 "sengal"  "sengat"  "sengau"  "senget"  "senggugut"  "sengguk"
                 "sengih"  "sengihan"  "sengit"  "sengkang"  "sengketa"  "sengsara"
                 "seni"  "seni"  "bahasa"  "seni"  "bina"  "seni"  "lukis"  "seni"
                 "ukir"  "seniman"  "seniwati"  "senja"  "senjakala"  "senjata"
                 "senjata"  "api"  "senjata"  "berat"  "senonoh"  "sentak"
                 "sental"  "sentap"  "senteng"  "sentiasa"  "sentosa"
                 "sentuh"  "sentuhan"  "senyap"  "senyap-senyap"
                 "senyum"  "senyuman"  "sepah"  "sepak"  "sepanduk"
                 "separa"  "separuh"  "sepatu"  "sepatu"  "besi"
                 "seperti"  "sepi"  "sepit"  "sepoi-sepoi"  "sepoi-sepoi"
                 "bahasa"  "sepuh"  "serabut"  "serah"  "serahan"  "serai"
                 "serak"  "seram"  "serambi"  "serampang"  "serang"  "serangan"
                 "serangga"  "Serani"  "serap"  "serapan"  "serapah"  "seraya"  "serba"
                 "serba"  "aneka"  "serba-serbi"  "serban"  "serbu"  "serbuan"  "serbuk"
                 "serempak"  "serentak"  "seret"  "sergah"  "sergahan"  "sergam"  "seri"  "Seri"
                 "Paduka"  "serigala"  "serik"  "sering"  "seringkali"  "seringai"  "serkap"
                 "serkup"  "serlah"  "serong"  "seronok"  "serpih"  "serpihan"  "serta"
                 "serta-merta"  "seru"  "seruan"  "seruling"  "sesah"  "sesak"  "sesal"
                 "sesalan"  "sesat"  "sesuai"  "sesungut"  "seterika"  "seteru"  "setia"
                 "setiausaha"  "setinggan"  "sewa"  "sewaan"  "sewa"  "beli"  "sfera"
                 "sia-sia"  "siak"  "sial"  "siamang"  "siang"  "siang"  "hari"  "siang-siang"
                 "siap"  "siap"  "sedia"  "siapa"  "siar"  "siaran"  "siasat"  "siasatan"
                 "siat"  "sibuk"  "sibur-sibur"  "sidai"  "sidang"  "sifar"  "sifat"
                 "sifir"  "sihat"  "sihir"  "sijil"  "sikap"  "sikat"  "siku"  "siku-siku"
                 "sila"  "silam"  "silang"  "silap"  "silau"  "silih"  "silu"  "simbah"
                 "simpan"  "simpanan"  "simpang"  "simpangan"  "simpang-siur"  "simpul"
                 "simpulan"  "simpulan"  "bahasa"  "sinar"  "sinaran"  "sindir"  "sindiran"
                 "singa"  "singgah"  "singgahsana"  "singgung"  "singkap"  "singkat"
                 "singkatan"  "singkir"  "singsing"  "sini"  "sinis"  "sipi"  "sipu"  "siput"
                 "siram"  "sirap"  "sirat"  "sirih"  "sirip"  "sisa"  "sisi"  "sisih"
                 "sisik"  "sisip"  "sisipan"  "sisir"  "siswa"  "sita"  "sitaan"  "situ"
                 "siul"  "siulan"  "siuman"  "soal"  "soalan"  "soal"  "selidik"  "sodok"
                 "sogok"  "sokong"  "sokongan"  "solek"  "sombong"  "sompek"  "sondol"  "songkok"
                 "songsang"  "sopan"  "sopan"  "santun"  "sorak-sorai"  "sorakan"  "sore"
                 "sorok"  "sorong"  "sorot"  "sorotan"  "sotong"  "sua"  "suai"  "suai"
                 "kenal"  "suam"  "suami"  "suap"  "suara"  "suara"  "hati"  "suara"  "ramai"
                 "suasana"  "suatu"  "subahat"  "subang"  "subuh"  "subur"  "suci"  "sudah"
                 "sudahlah"  "sudahnya"  "sudah-sudah"  "sudi"  "sudip"  "sudu"  "sudut"
                 "sugul"  "suhu"  "sujud"  "suka"  "suka"  "hati"  "suka"  "ria"  "sukacita"
                 "sukan"  "sukar"  "sukarela"  "sukarelawan"  "sukat"  "sukatan"  "suku"  "suku"
                 "kata"  "suku"  "bangsa"  "suku-sakat"  "sula"  "sulah"  "sulam"  "sulaman"
                 "suling"  "sulit"  "sultan"  "sultanah"  "suluh"  "sulung"  "sulur"  "sumbang"
                 "sumbangan"  "sumbangsih"  "sumbat"  "sumber"  "sumbing"  "sumbu"  "sumpah"  "sumpahan"
                 "sumpah-sumpah"  "sumpit"  "sumpitan"  "sumsum"  "sumur"  "sunat"  "sungai"
                 "sungguh"  "sungguh-sungguh"  "sungguhpun"  "sungkur"  "sungut"  "sungut-sungut"
                 "sunti"  "suntik"  "suntikan"  "sunting"  "suntuk"  "sunyi"  "supaya"
                 "surah"  "surai"  "suram"  "surat"  "suratkhabar"  "surau"  "suri"
                 "suri"  "rumahtangga"  "suria"  "suruh"  "suruhan"  "suruhanjaya"
                 "surut"  "susah"  "susah"  "hati"  "susah-susah"  "susila"  "susu"
                 "susuh"  "susuk"  "susuk"  "badan"  "susul"  "susulan"  "susun"  "susunan"
                 "susup"  "susur"  "susut"  "sutera"  "sutradara"  "swasta"  "Syaaban"
                 "syabas"  "syah"  "syahbandar"  "syahdan"  "syahid"  "syair"  "syaitan"
                 "syak"  "syarah"  "syarahan"  "syarat"  "syariah"  "syarikat"  "Syawal"
                 "syirik"  "syok"  "syor"  "syukur"  "syurga"  "taat"  "tabah"  "tabal"
                 "tabiat"  "tabii"  "tabik"  "tabir"  "tabuh"  "tabung"  "tabungan"
                 "tabung"  "uji"  "tabur"  "tadah"  "tadahan"  "tadbir"  "tadi"  "tadika"
                 "tafakur"  "tafsir"  "tagak"  "tagih"  "tahan"  "tahan"  "api"  "tahan"
                 "lasak"  "tahan"  "uji"  "tahanan"  "tahap"  "tahi"  "tahi"  "arak"
                 "tahi"  "judi"  "tahi"  "mata"  "tahi"  "telinga"  "tahniah"  "tahu"
                 "tahu-tahu"  "tahun"  "tahunan"  "tahyul"  "taja"  "tajaan"  "tajak"
                 "tajam"  "tajuk"  "tak"  "takabur"  "takal"  "takar"  "takat"
                 "takdir"  "takhta"  "takik"  "takjub"  "takkan"  "taklimat"  "takluk"
                 "takrif"  "taksir"  "taksiran"  "takung"  "takungan"  "takut"  "takwim"
                 "takziah"  "takzim"  "tala"  "talak"  "talam"  "tali"  "talian"  "talu"
                 "tamadun"  "tamak"  "taman"  "tamar"  "tamat"  "tambah"  "tambahan"
                 "tambak"  "tambang"  "tambat"  "tambatan"  "tampak"  "tampaknya"  "tampal"
                 "tampalan"  "tampan"  "tampar"  "tamparan"  "tampi"  "tampil"  "tampuk"
                 "tampung"  "tamsil"  "tamsilan"  "tamu"  "tanah"  "tanahair"  "tanah"
                 "gambut"  "tanah"  "gembur"  "tanah"  "jajahan"  "tanah"  "liat"  "tanah"
                 "pamah"  "tanah"  "tumpah"  "darah"  "tanak"  "tanam"  "tanaman"
                 "tanam-tanaman"  "tanda"  "tandan"  "tandang"  "tandas"  "tandatangan"
                 "tanding"  "tandu"  "tanduan"  "tanduk"  "tangan"  "tangga"
                 "tanggal"  "tanggap"  "tanggapan"  "tangguh"  "tangguk"  "tanggung"
                 "tanggungan"  "tanggungjawab"  "tangis"  "tangisan"  "tangkai"
                 "tangkai"  "jering"  "tangkal"  "tangkap"  "tangkapan"  "tangkas"
                 "tangkis"  "tanglung"  "tangsi"  "tani"  "tanjak"  "tanjung"  "tanpa"
                 "tanya"  "tapa"  "tapak"  "tapis"  "tapisan"  "tara"  "taraf"
                 "tarah"  "tari"  "tarian"  "tarik"  "tarikh"  "taring"  "taruh"
                 "tarung"  "tasik"  "tata"  "tataacara"  "tatabahasa"  "tatacara"
                 "tatahukum"  "tatasusila"  "tatatertib"  "tatah"  "tatahan"  "tatang"
                 "tatap"  "tatapan"  "tatih"  "tatkala"  "taubat"  "taufan"  "tauge"
                 "tauhu"  "tauke"  "taulan"  "tauliah"  "taun"  "Taurat"  "taup"  "taut"  "tawa"
                 "tawan"  "tawanan"  "tawar"  "tawaran"  "tawar"  "hati"  "tawar"  "hambar"  "tawar-menawar"
                 "tawarikh"  "tayang"  "tayangan"  "tebal"  "tebang"  "tebar"  "tebas"  "tebing"  "tebu"
                 "tebuan"  "tebuk"  "tebus"  "tebusan"  "teduh"  "tedung"  "tegah"  "tegahan"  "tegak"  "tegang"
                 "tegap"  "tegar"  "tegas"  "tegasan"  "teguh"  "teguk"  "tegun"  "tegur"  "teguran"  "teh"
                 "teka"  "teka-teki"  "tekaan"  "tekad"  "tekak"  "tekan"  "tekanan"  "tekap"  "tekat"  "teko"
                 "tekong"  "tekukur"  "tekun"  "telaah"  "teladan"  "telaga"  "telagah"  "telah"  "telahan"
                 "telan"  "telangkup"  "telanjang"  "telap"  "telapak"  "telatah"  "telekung"  "telentang"
                 "telinga"  "telingkah"  "teliti"  "teluk"  "telungkup"  "telunjuk"  "telur"  "telur"  "dadar"
                 "telur"  "masin"  "telut"  "teman"  "temasya"  "tembaga"  "tembaga"  "merah"  "tembaga"  "kuning"
                 "tembaga"  "perunggu"  "tembaga"  "putih"  "tembak"  "tembak-menembak"  "tembakan"  "tembakau"  "tembam"
                 "tembelang"  "temberang"  "tembikai"  "tembikar"  "tembok"  "tembolok"  "tembung"  "tembuni"
                 "tembus"  "tempa"  "tempah"  "tempahan"  "tempang"  "tempat"  "tempatan"  "tempayan"
                 "tempel"  "tempelak"  "tempeleng"  "tempiar"  "tempik"  "tempikan"  "tempik-sorak"  "tempoh"
                 "tempoyak"  "tempua"  "tempuh"  "tempuling"  "tempur"  "tempurung"  "temu"  "temu"  "duga"
                 "temu"  "ramah"  "tenaga"  "tenang"  "tenat"  "tendang"  "tendangan"  "tengadah"  "tengah"
                 "tengah"  "hari"  "tenggala"  "tenggara"  "tenggek"  "tenggelam"  "tengger"  "tenggiling"
                 "tengik"  "tengkar"  "tengking"  "tengkingan"  "tengkolok"  "tengkorak"  "tengku"  "tengkuk"
                 "tengok"  "tentang"  "tentangan"  "tentera"  "tenteram"  "tentu"  "tenun"  "tenung"
                 "tenungan"  "tenusu"  "tepak"  "tepat"  "tepi"  "tepis"  "tepu"  "tepuk"  "tepukan"
                 "gemuruh"  "tepung"  "tera"  "terajang"  "teraju"  "terang"  "terang-benderang"
                 "terang-terang"  "terap"  "teras"  "teratai"  "teratai"  "kecil"  "teratak"  "terbang"
                 "terbit"  "terbitan"  "teriak"  "terik"  "terima"  "terima"  "kasih"  "terima"  "salah"
                 "terjemah"  "terjemahan"  "terjun"  "terkam"  "ternak"  "ternakan"  "teroka"  "terompah"
                 "teropong"  "terowong"  "terpa"  "tertib"  "tertib"  "nikah"  "tertib"  "sopan"  "terubuk"
                 "teruk"  "teruna"  "terung"  "terus"  "terusan"  "terus-menerus"  "tetak"  "tetakan"
                 "tetamu"  "tetangga"  "tetap"  "tetapi"  "tetas"  "tetek"  "tetes"  "tetesan"  "tewas"
                 "tiada"  "tiang"  "tiap"  "tiarap"  "tiba"  "tiba-tiba"  "tidak"  "tidak"  "apa"  "tidak"
                 "apa-apa"  "tidur"  "tidur"  "ayam"  "tidur"  "mati"  "tiga"  "tikai"  "tikam"  "tikaman"
                 "tikam"  "dadu"  "tikar"  "tikus"  "tilam"  "tilik"  "tilikan"  "tilik"  "nasib"  "timah"
                 "timang"  "timangan"  "timba"  "timbal"  "timbalan"  "timbang"  "timbang"  "rasa"
                 "timbul"  "timbun"  "timbus"  "timpa"  "timpaan"  "timpal"  "timun"  "timur"  "tindak"
                 "tindakan"  "tindak"  "balas"  "tindak"  "tanduk"  "tindas"  "tindasan"  "tindih"
                 "tindik"  "tinggal"  "tinggi"  "tingkah"  "tingkahan"  "tingkap"  "tingkat"  "tinkatan"
                 "tinjau"  "tinjauan"  "tinju"  "tinta"  "Tionghua"  "Tiongkok"  "tipis"  "tipu"
                 "tirai"  "tiram"  "tiri"  "tiris"  "tiru"  "tiruan"  "tirus"  "titah"  "titi"
                 "titian"  "titik"  "titikberat"  "titik"  "dua"  "titis"  "titisan"  "tiup"
                 "tiupan"  "tocang"  "todak"  "togel"  "tohor"  "tok"  "toko"  "tokoh"  "tokok"
                 "tokong"  "tolak"  "tolakan"  "tolak"  "ansur"  "tolak"  "bala"  "toleh"  "tolok"
                 "tolol"  "tolong"  "tolong-menolong"  "tombak"  "tombol"  "tompok"  "tong"  "tonggek"
                 "tongkang"  "tongkat"  "tongkol"  "tonjol"  "tonton"  "tontonan"  "tonyoh"  "topang"
                 "topeng"  "topi"  "toreh"  "torehan"  "toyol"  "trengkas"  "tua"  "tua-tua"  "tuah"
                 "tuai"  "tuak"  "tuala"  "tuan"  "tuan"  "rumah"  "tuang"  "tuanku"  "tuas"
                 "tuba"  "tubi"  "tubuh"  "tubuh"  "badan"  "tuduh"  "tuduhan"  "tuding"  "tudung"
                 "tugas"  "tugasan"  "tugu"  "Tuhan"  "tujah"  "tuju"  "tujuan"  "tujuh"  "tukang"
                 "tukar"  "tukaran"  "tukar"  "ganti"  "tukul"  "tulang"  "tular"  "tulat"  "tulen"
                 "tuli"  "tulis"  "tulisan"  "tulus"  "tumbang"  "tumbesar"  "tumbuh"  "tumbuhan"
                 "tumbuh-tumbuhan"  "tumbuk"  "tumis"  "tumit"  "tumpah"  "tumpahan"  "tumpah"
                 "darah"  "tumpang"  "tumpangan"  "tumpas"  "tumpat"  "tumpu"  "tumpuan"
                 "tumpul"  "Tun"  "tunai"  "tunang"  "tunas"  "tunda"  "tunduk"  "tunggak"
                 "tunggakan"  "tunggal"  "tunggang"  "tunggu"  "tunggul"  "tungku"  "tungkus"
                 "lumus"  "tunjal"  "tunjam"  "tunjuk"  "tunjuk"  "ajar"  "tunjuk"  "perasaan"
                 "tuntun"  "tuntut"  "tuntutan"  "tupai"  "turas"  "turun"  "turunan"
                 "turun-temurun"  "turus"  "turut"  "turutan"  "tusuk"  "tut"  "tutup"
                 "tutur"  "uak"  "uap"  "ubah"  "uban"  "ubat"  "ubi"  "ubin"  "ubun"
                 "ubur-ubur"  "ucap"  "udang"  "udara"  "udik"  "ufuk"  "ugut"  "uji"
                 "ukir"  "ukur"  "ulam"  "ulama"  "ulang"  "ular"  "ulas"  "ulat"  "uli"
                 "ulit"  "ulung"  "umang-umang"  "umat"  "umbang"  "umbi"  "umbuk"  "umbut"
                 "umpama"  "umpan"  "umpat"  "umpil"  "umum"  "umur"  "undan"  "undang"
                 "undang-undang"  "undi"  "undur"  "unggas"  "unggis"  "unggul"  "unggun"
                 "ungka"  "ungkai"  "ungkap"  "ungkit"  "ungu"  "unjuk"  "unjur"  "unsur"
                 "unta"  "untai"  "untuk"  "untung"  "untut"  "upacara"  "upah"  "upaya"
                 "ura"  "urai"  "urat"  "uri"  "urus"  "urut"  "usaha"  "usai"  "usang"
                 "usap"  "usia"  "usik"  "usir"  "usul"  "usus"  "utama"  "utara"  "utas"
                 "utuh"  "utus"  "uzur"  "vaksin"  "van"  "vanila"  "video"  "virus"  "visa"
                 "vitamin"  "wabak"  "wacana"  "wafat"  "waham"  "wahyu"  "waja"  "wajah"
                 "wajar"  "wajib"  "wajik"  "wakaf"  "wakil"  "waktu"  "walau"  "walaupun"
                 "walhal"  "walhasil"  "wali"  "wang"  "wangi"  "wanita"  "wap"  "warak"  "waras"
                 "wargakota"  "warganegara"  "waris"  "warkah"  "warna"  "warta"  "wartawan"  "warung"
                 "wasangka"  "wasiat"  "waspada"  "waswas"  "watak"  "watan"  "watikah"  "wau"  "wawancara"
                 "wawasan"  "wayang"  "wayang"  "gambar"  "wayang"  "kulit"  "wenang"  "wibawa"  "wilayah"
                 "wira"  "wisma"  "wujud"  "X-ray"  "ya"  "Yahudi"  "yakin"  "yang"  "Yang"  "Teramat"
                 "Mulia"  "yatim"  "yayasan"  "yu"  "yuran"  "zahid"  "zaitun"  "zakar"  "zakat"
                 "zalim"  "zaman"  "zamrud"  "zapin"  "zarah"  "zat"  "ziarah"  "zina"  "zirafah"
                 "Zuhal"  "Zuhrah"  "zuhur"  "Zulhijah"  "Zulkaedah"  "zuriat"] )

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println "Testing"))


